import Link from "next/link";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
          <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black min-h-screen`}>
            {/* Tech-oriented Navigation Bar */}
            <nav className="w-full flex items-center justify-between px-6 py-4 bg-gradient-to-r from-blue-900 via-gray-900 to-black shadow-lg z-20 sticky top-0">
              <Link href="/" className="text-2xl font-bold tracking-tight text-white hover:text-blue-400 transition">COSMOS</Link>
              <div className="flex gap-6 text-lg font-medium">
                <Link href="/features" className="text-gray-200 hover:text-blue-400 transition">Features</Link>
                <Link href="/about" className="text-gray-200 hover:text-blue-400 transition">About</Link>
                <Link href="/contact" className="text-gray-200 hover:text-blue-400 transition">Contact</Link>
              </div>
            </nav>
            <main className="w-full flex-1 flex flex-col">{children}</main>
          </body>
        </html>
  );
}
